[package]
name = "workers"
version = "0.1.0"
authors = ["Endel Dreyer <endel.dreyer@gmail.com>"]

[dependencies]
curl = "0.2.10"
threadpool = "0.1.4"
rustc-serialize = "0.3"

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"

# [dev-dependencies]
